### ISSUE TITLE
Header-issue

### ISSUE THREAD

**Issue by sijin-raj** [Kithackclub/Hacktoberfest#7]
# issue on the header 
## want update the navbar 

<nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
           
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>

**Comment by sijin-raj** [comment]
yes @dyarawilliams  you can , but build like this 👇
![Screen Shot 2021-10-12 at 10 13 53 PM](https://user-images.githubusercontent.com/54431616/136996688-332dfe9a-f802-4e24-9679-1cebebdf9ec3.png)

**Comment by sijin-raj** [comment]
you can see the image inside the assets file

**Comment by dyarawilliams** [comment]
Okay

**Comment by sijin-raj** [comment]
thank you @dyarawilliams  for your Contribution :)
